services:
  - type: web
    name: GraderDatabase
    env: docker
    plan: free
    dockerfilePath: ./GraderDatabase/Dockerfile
    buildCommand: ""
    startCommand: "docker-entrypoint.sh postgres"
    envVars:
      - key: POSTGRES_DB
        fromSecret: DB_NAME
      - key: POSTGRES_USER
        fromSecret: DB_USERNAME
      - key: POSTGRES_PASSWORD
        fromSecret: DB_PASSWORD

  - type: web
    name: GraderRabbitMQ
    env: docker
    plan: free
    dockerfilePath: ./GraderRabbitMQ/Dockerfile
    buildCommand: ""
    startCommand: "rabbitmq-server"
    envVars:
      - key: RABBITMQ_DEFAULT_USER
        fromSecret: RABBIT_USERNAME
      - key: RABBITMQ_DEFAULT_PASS
        fromSecret: RABBIT_PASSWORD

  - type: web
    name: GraderRedis
    env: docker
    plan: free
    dockerfilePath: ./GraderRedis/Dockerfile
    buildCommand: ""
    startCommand: "redis-server"

  - type: web
    name: GraderBackend
    env: docker
    plan: free
    dockerfilePath: ./GraderBackend/Dockerfile
    buildCommand: ""
    startCommand: "sh -c 'sleep 30 && java -jar /app/backend.jar'"
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://GraderDatabase:5432/${DB_NAME}"
      - key: SPRING_DATASOURCE_USERNAME
        fromSecret: DB_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
        fromSecret: DB_PASSWORD
      - key: SPRING_REDIS_HOST
        value: "GraderRedis"
      - key: SPRING_REDIS_PORT
        value: "6379"
      - key: SPRING_RABBITMQ_HOST
        value: "GraderRabbitMQ"
      - key: SPRING_RABBITMQ_PORT
        value: "5672"
      - key: SPRING_RABBITMQ_USERNAME
        fromSecret: RABBIT_USERNAME
      - key: SPRING_RABBITMQ_PASSWORD
        fromSecret: RABBIT_PASSWORD
      - key: JWT_KEY_ID
        fromSecret: JWT_KEY_ID
      - key: MAIL_USERNAME
        fromSecret: MAIL_USERNAME
      - key: MAIL_PASSWORD
        fromSecret: MAIL_PASSWORD
      - key: AWS_ACCESS_KEY
        fromSecret: AWS_ACCESS_KEY
      - key: AWS_SECRET_KEY
        fromSecret: AWS_SECRET_KEY
      - key: PORT
        value: "8080"

  - type: web
    name: GraderWorker
    env: docker
    plan: free
    dockerfilePath: ./GraderWorkerApplication/docker/Dockerfile.worker
    buildCommand: ""
    startCommand: "sh -c 'sleep 45 && java -jar /app/worker.jar'"
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://GraderDatabase:5432/${DB_NAME}"
      - key: SPRING_DATASOURCE_USERNAME
        fromSecret: DB_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
        fromSecret: DB_PASSWORD
      - key: SPRING_REDIS_HOST
        value: "GraderRedis"
      - key: SPRING_REDIS_PORT
        value: "6379"
      - key: SPRING_RABBITMQ_HOST
        value: "GraderRabbitMQ"
      - key: SPRING_RABBITMQ_PORT
        value: "5672"
      - key: SPRING_RABBITMQ_USERNAME
        fromSecret: RABBIT_USERNAME
      - key: SPRING_RABBITMQ_PASSWORD
        fromSecret: RABBIT_PASSWORD
      - key: JWT_KEY_ID
        fromSecret: JWT_KEY_ID
      - key: MAIL_USERNAME
        fromSecret: MAIL_USERNAME
      - key: MAIL_PASSWORD
        fromSecret: MAIL_PASSWORD
      - key: AWS_ACCESS_KEY
        fromSecret: AWS_ACCESS_KEY
      - key: AWS_SECRET_KEY
        fromSecret: AWS_SECRET_KEY

  - type: web
    name: GraderRunner
    env: docker
    plan: free
    dockerfilePath: ./GraderWorkerApplication/docker/Dockerfile.runner
    buildCommand: ""
    startCommand: "sh -c 'tail -f /dev/null'"

  - type: web
    name: GraderFrontend
    env: docker
    plan: free
    dockerfilePath: ./GraderFrontend/Dockerfile
    buildCommand: ""
    startCommand: 'sh -c ''sleep 60 && nginx -g "daemon off;"'''
    envVars:
      - key: BACKEND_URL
        value: "https://GraderBackend.onrender.com"
      - key: PORT
        value: "80"
