services:
  - type: web
    name: grader-database
    env: docker
    plan: free
    dockerImage: postgres:15
    startCommand: ""
    envVars:
      - key: POSTGRES_DB
        fromSecret: DB_NAME
      - key: POSTGRES_USER
        fromSecret: DB_USERNAME
      - key: POSTGRES_PASSWORD
        fromSecret: DB_PASSWORD

  - type: web
    name: rabbitmq
    env: docker
    plan: free
    dockerImage: rabbitmq:3.13-management
    startCommand: ""
    envVars:
      - key: RABBITMQ_DEFAULT_USER
        fromSecret: RABBIT_USERNAME
      - key: RABBITMQ_DEFAULT_PASS
        fromSecret: RABBIT_PASSWORD

  - type: web
    name: redis
    env: docker
    plan: free
    dockerImage: redis:7
    startCommand: ""

  - type: web
    name: grader-backend
    env: docker
    plan: free
    buildCommand: "cd GraderBackend && ./gradlew build"
    startCommand: "java -jar GraderBackend/build/libs/backend.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://grader-database:5432/${DB_NAME}"
      - key: SPRING_DATASOURCE_USERNAME
        fromSecret: DB_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
        fromSecret: DB_PASSWORD
      - key: SPRING_REDIS_HOST
        value: "redis"
      - key: SPRING_RABBITMQ_HOST
        value: "rabbitmq"
      - key: SPRING_RABBITMQ_PORT
        value: "5672"
      - key: SPRING_RABBITMQ_USERNAME
        fromSecret: RABBIT_USERNAME
      - key: SPRING_RABBITMQ_PASSWORD
        fromSecret: RABBIT_PASSWORD
      - key: JWT_KEY_ID
        fromSecret: JWT_KEY_ID
      - key: MAIL_USERNAME
        fromSecret: MAIL_USERNAME
      - key: MAIL_PASSWORD
        fromSecret: MAIL_PASSWORD
      - key: AWS_ACCESS_KEY
        fromSecret: AWS_ACCESS_KEY
      - key: AWS_SECRET_KEY
        fromSecret: AWS_SECRET_KEY

  - type: web
    name: grader-worker
    env: docker
    plan: free
    buildCommand: "cd GraderWorkerApplication && ./gradlew build"
    startCommand: "sh -c 'sleep 10 && java -jar GraderWorkerApplication/build/libs/worker.jar'"
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://grader-database:5432/${DB_NAME}"
      - key: SPRING_DATASOURCE_USERNAME
        fromSecret: DB_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
        fromSecret: DB_PASSWORD
      - key: SPRING_REDIS_HOST
        value: "redis"
      - key: SPRING_RABBITMQ_HOST
        value: "rabbitmq"
      - key: SPRING_RABBITMQ_PORT
        value: "5672"
      - key: SPRING_RABBITMQ_USERNAME
        fromSecret: RABBIT_USERNAME
      - key: SPRING_RABBITMQ_PASSWORD
        fromSecret: RABBIT_PASSWORD
      - key: JWT_KEY_ID
        fromSecret: JWT_KEY_ID
      - key: MAIL_USERNAME
        fromSecret: MAIL_USERNAME
      - key: MAIL_PASSWORD
        fromSecret: MAIL_PASSWORD
      - key: AWS_ACCESS_KEY
        fromSecret: AWS_ACCESS_KEY
      - key: AWS_SECRET_KEY
        fromSecret: AWS_SECRET_KEY

  - type: web
    name: grader-runner
    env: docker
    plan: free
    buildCommand: "cd GraderWorkerApplication && ./gradlew build"
    startCommand: "sh -c 'tail -f /dev/null'"
    volumes:
      - name: grader-runner-workspace
        mountPath: /workspace

  - type: web
    name: grader-frontend
    env: docker
    plan: free
    buildCommand: "cd GraderFrontend && npm install && npm run build"
    startCommand: 'sh -c ''sleep 10 && nginx -g "daemon off;"'''
    envVars:
      - key: BACKEND_URL
        value: "http://grader-backend:8080"

volumes:
  - name: grader-runner-workspace
